# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run build
        env:
          CI: true

      - if: ${{ matrix.node-version == '18.x' }}
        name: Get Coverage for badge
        run: |
          SUMMARY="$(npm test -- --updateSnapshot --coverage --coverageReporters='text-summary' --watchAll=false | tail -2 | head -1)"
          COVERAGE=$(echo "$SUMMARY" | awk -F'[:%]' '{print $2}' | awk '{$1=$1;print}' | awk '{print $0"%"}')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          REF=${{ github.ref }}
          IFS='/' read -ra PATHS <<< "$REF"
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          echo $BRANCH_NAME
          echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV

      - if: ${{ matrix.node-version == '18.x' }}
        name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: cdc60bed264cf5afd17e322cee8feee2
          filename: legalaid-web__${{ env.BRANCH }}.json
          label: Test Coverage
          message: ${{ env.COVERAGE }} # Set to 0% if COVERAGE is empty
          color: green
          namedLogo: jest
